version: '2'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - CLIENT_URL=http://localhost:3000
      - FASTAPI_URL=http://fastapi:8000
      - NODE_ENV=development
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    env_file:
      - ./client/.env
