services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    autoDeploy: true

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    autoDeploy: true

  - type: web
    name: fastapi
    env: docker
    plan: free
    dockerContext: ./fastapi_server
    dockerfilePath: ./fastapi_server/Dockerfile
    autoDeploy: true
